=== Rmittal21/MCA-WEB-TECH-LAB-WORK/LAB7/catalogue.xsd
<?xml version="1.0"?>

<xs:schema version="1.0" xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="catalogue">
        <xs:complexType mixed="true">
            <xs:sequence>
                <xs:element name="cd" minOccurs="3" maxOccurs="10"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="cd">
        <xs:complexType mixed ="true">
           <xs:sequence>
            <xs:element name="title" type="xs:string"/>
            <xs:element name="artist" type="xs:string"/>
            <xs:element name="country" type="xs:string"/>
            <xs:element name="company" type="xs:string"/>
            <xs:element name="price">
            <xs:simpleType>
                <xs:restriction base="xs:decimal">
                    <xs:minInclusive value="10.00"/>
                    <xs:maxExclusive value="110.00"/>
                </xs:restriction>
            </xs:simpleType>
            </xs:element>
           </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== Rmittal21/MCA-WEB-TECH-LAB-WORK/LAB7/catalogue.xml
<?xml version="1.0" encoding="UTF-8"?>

<catalogue xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="catalogue.xsd">>
    <cd>
        <title>Empire Burlesque</title>
        <artist>Bob Dylan</artist>
        <country>USA</country>
        <company>Columbia</company>
        <price>10.90</price>
        
    </cd>
    
    <cd>
        <title>Hide your Heart</title>
        <artist>Bonnie Tyler</artist>
        <country>UK</country>
        <company>CBS Records</company>
        <price>19.90</price>
    </cd>
    
    <cd>
        <title>Greatest Hits</title>
        <artist>Dolly Parton</artist>
        <country>USA</country>
        <company>RCA</company>
        <price>29.90</price>
    </cd>
</catalogue>
